name: don
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_localizations:
    sdk: flutter
  
  image_picker: ^0.8.3+3
  flutter_spinkit: ^5.1.0
  permission_handler: ^6.0.1+1
  google_fonts: ^2.1.0
  dio: ^4.0.1
  json_annotation: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  freezed: ^0.15.0+1
  freezed_annotation: ^0.12.0
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
